### ISSUE TITLE
Indexing the genome

### ISSUE THREAD

**Issue by sebel76** [atulkakrana/phasTER#3]
Hi Atul,

In response to your email of yesterday. I weird, it works on your computer… Yes, I used ‘python3’ and bowtie ‘v1’. 

As troubleshooting, I try some things. 
(1) Build the index by myself and indicate the path of the index in the ‘phaser.set’ file. It is not working.
(2) I used only for the 7 chromosomes without unassembled scaffold and contig. It is not working.
(3) I download a second time the genome and tried against. It is not working.

See the log information bellow:

mbpdesebastien:phasiRNA sebel76$ python3 phaser

#### Verifying User Authorization ################
Hello 'sebel76' - Please report issues at: https://github.com/atulkakrana/phasTER/issues

#### Fn: checkLibs #####################
--Python v3.0 or higher          : found
--Perl v5.14 or higher           : found
--Bowtie (v1)                    : found
--Scalar::Util (perl)            : found
--Data::Dumper (perl)            : found
--Parallel::ForkManager (perl)   : found
--Getopt::Long (perl)            : found
--phasTER Core                   : found

#### Fn: Settings Reader ####################
User Input runType:               G
User Input reference location:    /Users/sebel76/NucleicAcid/ensembl_relase31/dna/HvuASM32608v1Chr.fa
User Input Libs:                  ['UNMDay0clippedCollapsed.txt']
User Input to auto fetch libs:    T
User Input for phase length:      21
User Input index location:        

#### 7 threads assigned to one lib #########

This is first run - create index

#### Fn: indexBuilder #########################
Reference file located - Preparing to create index
PHASER uses FASTA header as key for identifying the phased loci
Cleaning header '/Users/sebel76/NucleicAcid/ensembl_relase31/dna/HvuASM32608v1Chr.fa' reference FASTA file
Traceback (most recent call last):
  File "phaser.py", line 990, in <module>
  File "phaser.py", line 854, in main
  File "phaser.py", line 572, in indexBuilder
  File "phaser.py", line 653, in FASTAClean
OSError: [Errno 22] Invalid argument

Have you an idea how I can resolve the problem?
Thanks,
Sébastien

**Comment by atulkakrana** [comment]
Sebastian,

The issue is not related to indexing. Phaser is trying to check your FASTA file, and clean messy headers, if any. It seems its not being able to locate your FASTA file. Which operating system are you using? and could you please post contents of your settings file (phaser.set), only the settings portion of it?

Atul

**Comment by atulkakrana** [comment]
I believe *phasTER* binaries are in the same folder as your reference FASTA and sRNA library. If that is true, then can you provide reference path like this (in settings file):

`@reference      = ./Hordeum_vulgare.ASM32608v1.fa`

Sometimes the $PATH variable is set differently (or incorrectly) on Linux systems, and do not represent true location of a file. Providing the path, as I included above should fix the problem in such cases. 

Atul

**Comment by sebel76** [comment]
Hello Atul,

This is the answer of your first post: I work with a Unix operating system on a mac os x 10.12.2. See the contents of my settings file (phaser.set):

<<< Settings file for phaser script >>>

<<< Mandatory Settings, value in text, see descriptions below >>>
@runType        = G
@reference      = /Users/sebel76/NucleicAcid/ensembl_relase31/dna/HvuASM32608v1Chr.fa
@userLibs       = UNMDay0clippedCollapsed.txt
@libFormat      = T					
@phase          = 21

Thanks,
Sébastien

**Comment by sebel76** [comment]
Hello Atul,

This is the answer of your second post: I tried to change the folder of the reference genome fasta file and put this one in the same folder of the phasTER binaries sRNA library. I use you recommandation by changing the setting file:

@reference = ./Hordeum_vulgare.ASM32608v1.fa

See the contents of my settings file (phaser.set):

<<< Settings file for phaser script >>>

<<< Mandatory Settings, value in text, see descriptions below >>>
@runType        = G
@reference      = ./HvuASM32608v1Chr.fa
@userLibs       = UNMDay0clippedCollapsed.txt
@libFormat      = T					
@phase          = 21

Then, I run the phaser script and I receive the same same message error:

mbpdesebastien:phasiRNA sebel76$ python3 phaser

#### Verifying User Authorization ################
Hello 'sebel76' - Please report issues at: https://github.com/atulkakrana/phasTER/issues

#### Fn: checkLibs #####################
--Python v3.0 or higher          : found
--Perl v5.14 or higher           : found
--Bowtie (v1)                    : found
--Scalar::Util (perl)            : found
--Data::Dumper (perl)            : found
--Parallel::ForkManager (perl)   : found
--Getopt::Long (perl)            : found
--phasTER Core                   : found

#### Fn: Settings Reader ####################
User Input runType:               G
User Input reference location:    ./HvuASM32608v1Chr.fa
User Input Libs:                  ['UNMDay0clippedCollapsed.txt']
User Input to auto fetch libs:    T
User Input for phase length:      21
User Input index location:        

#### 7 cores reserved for analysis #########
#### 7 threads assigned to one lib #########

This is first run - create index

#### Fn: indexBuilder #########################
Reference file located - Preparing to create index
PHASER uses FASTA header as key for identifying the phased loci
Cleaning header './HvuASM32608v1Chr.fa' reference FASTA file
Traceback (most recent call last):
  File "phaser.py", line 990, in <module>
  File "phaser.py", line 854, in main
  File "phaser.py", line 572, in indexBuilder
  File "phaser.py", line 653, in FASTAClean
OSError: [Errno 22] Invalid argument
mbpdesebastien:phasiRNA sebel76$ 

I don't understand... Thinks you that is the reference file header that create the problem?

Thanks,
Sébastien

**Comment by atulkakrana** [comment]
This is very strange, phasTER is not being able to find the file !! I must say that we never test software on MacOS and it's pretty common. But since it's Unix the scripts should just work fine. Unfortunately, I can't test it on Mac.

Please send me the list of files from you analysis folder. Just navigate to folder where you have binaries and reference FASTA and execute `ls -lah`. Send me the output. Also, please send me the output of `pwd` command, execute it from same folder. 

Atul

**Comment by sebel76** [comment]
Sorry for the delay of response...

See bellow the information requested:

MacBook-Pro-de-Sebastien:phasiRNA sebel76$ ls -lah
total 8000880
drwxr-xr-x  14 sebel76  staff   476B 20 fév 14:27 .
drwxr-xr-x  15 sebel76  staff   510B 20 fév 14:26 ..
-rw-r--r--@  1 sebel76  staff   6,0K 20 fév 14:26 .DS_Store
-rw-r--r--   1 sebel76  staff    52K 26 déc 20:19 .Rhistory
-rw-r--r--   1 sebel76  staff     0B 20 fév 14:27 HvuASM32608v1Chr.clean.fa
-rw-r--r--@  1 sebel76  staff   3,7G 13 fév 18:59 HvuASM32608v1Chr.fa
-rw-r--r--   1 sebel76  staff     9B 20 fév 14:27 HvuASM32608v1Chr.summ.txt
-rw-r--r--   1 sebel76  staff   122M  8 fév 11:13 UNMDay0clippedCollapsedTagCount.txt
-rwxr-xr-x@  1 sebel76  staff   821K  7 mai  2012 bowtie
-rwxr--r--   1 sebel76  staff    42K  7 fév 09:43 collapser
-rwxr--r--   1 sebel76  staff    23K  7 fév 09:43 phaser
-rw-r--r--@  1 sebel76  staff   1,2K 13 fév 10:27 phaser.set
-rwxr--r--   1 sebel76  staff    37K  7 fév 09:43 revferno
-rw-r--r--   1 sebel76  staff     0B 20 fév 14:27 runtime_02_20_14_27

MacBook-Pro-de-Sebastien:phasiRNA sebel76$ pwd
/Users/sebel76/paper/4/phasiRNA


Thanks for your help! 
Sébastien
